### ISSUE TITLE
Upgrade Yarn to Yarn Berry

### ISSUE THREAD

**Issue by noisypigeon** [noisypigeon-inc/pigeon-fi#3]
Upgrade Yarn to Yarn Berry. Only the `releases` dir and `.yarn/install-state.gz` should be committed. Use .gitignore to exclude the rest.

https://yarnpkg.com/getting-started/migration
https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

**Comment by Dirkulese** [comment]
Upgrade yarn to yarn berry, completing this issue
